# Generated by Django 5.1.3 on 2024-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('isbn_number', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
